### ISSUE TITLE
Conversion amount occasionally much too small

### ISSUE THREAD

**Issue by AFishNamedFish** [robdejonge/Launchbar-Currency-Conversion#3]
I want to thank robdejonge, as this code is brilliant.

I have noticed that sometimes I will want to convert, for example, 5000 USD to MXN.

Instead of the `gsToAmt` result being around about `91845.50`, it is simply `91`. In other words, the conversion amount is too small.

But, then, I will try the same calculation 2 minutes later, and your code will work properly again.

The decimal location for the incorrect output is **always** three spaces to the left of the decimal location of the correct output.

I have not been able to diagnose the issue.

**Comment by robdejonge** [comment]
Thanks for reporting this.

The script assumed a decimal point always existed in the result returned from Google. It uses the location of this decimal point to determine where to cut off the string so that the result displayed has only 2 decimals. The problem you reported occurred when the result returned from Google did not contain a decimal point. In those cases, the `offset` command in line 50 would return 0 and the `set gsToAmt` would truncate the result 2 characters to the right of that. The cut now only happens when there is a decimal point in the result returned from Google. 

I could not reproduce the exact situation you reported; you said a result containing a decimal point would get truncated. I'm going to assume your numbers were anecdotal and I have indeed addressed the problem.
